sudo: required
services:
   - docker

before_install:
   - docker build -f Dockerfile.dev . --tag portasanych/frontend_app_docker_udemy:latest

script:
   - docker run portasanych/frontend_app_docker_udemy CI=true npm run test -- --coverage